spring:
  datasource:
    url: jdbc:h2:mem:fooddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

jwt:
  secret: verysecretkeyforjwtdontusethisinprod
  expirationMs: 86400000